### PR TITLE
Rejected products disappear

### LINKED ISSUE #29: Rejected Products disappear
### Products disappear
When we run the **update all effected products now** action in the **Translations**  page, we may encounter **_rejected products_** which are pushed back into the app to be fixed.
When we now create a new _Base Product/ Component/ Material/ Metatag_ those rejected products **disappear**.
### Products not rejected anymore?
Furthermore when we now run **update all effected products now** again, the rejected products will not show again, even though they are not fixed yet.
### Notification text wrong
When we have rejected products, the confirmation message will be `Congratulations, we just updated XX Product pages. To ensure that we don't break Product pages by accident, we rejected some Products from the automatic update. Please review and save them manually.` The second half (_To ensure that we ...._ ) is supposed **ONLY** to show when we have rejected products but **sometimes** it appears as well when we don't.

### PR DESCRIPTION
**Pull request by lalitaCF**
close #29

### CODE REVIEW

File: assets/app.js [hunk 1]
```diff
@@ -75,6 +75,7 @@ new Vue({
         Multiselect: window.VueMultiselect.default
     },
     data: {
+        rawRejectedProducts: null,
```
Comment (Solomonic) [inline assets/app.js]: just call it `rejectedProducts`

File: assets/app.js [hunk 2]
```diff
@@ -1611,6 +1643,96 @@ new Vue({
             })
             return false
 
+        },
+        resolveRejectedProducts: function () {
+            this.products = [];
+            console.log("test", this.rawRejectedProducts)
```
Comment (Solomonic) [inline assets/app.js]: remove `console.log()`

File: components/templates/template.html.twig [hunk 3]
```diff
@@ -22,6 +22,10 @@
             <span>[[message.message]]</span>
             <i class="fa fa-eye-slash fa-pull-right" aria-hidden="true" @click="hideMessage(message)" ></i>
         </div>
+        <div v-if="Object.keys(getRejectedProducts).length - 3 > 0" class="alert alert-warning">
```
Comment (Solomonic) [inline components/templates/template.html.twig]: please explain

**Review by Solomonic — CHANGES_REQUESTED** [review]

File: assets/app.js [hunk 4]
```diff
@@ -1611,6 +1643,96 @@ new Vue({
...
+            products = this.rawRejectedProducts
+            //action for getting products
+            var product_names = []
+            for (var key in products) {
+                if (key !== 'success' && key !== 'metatags' && key !== 'materials' && 'propertyFormula' in products[key]) {
```
Comment (cyberhck) [inline assets/app.js]: nit(optional): not a biggy, but for DRY, I'd do something like `['success', 'metatags', 'materials'].indexOf(key) === -1`, actually I'd define a separate constant so in future if key can't be say, 'attributes' or something, I could just add an entry in array :slightly_smiling_face: , and this line could be shorter.

Comment (Solomonic) [reply assets/app.js]: I agree

File: assets/app.js [hunk 5]
```diff
@@ -737,6 +770,16 @@ new Vue({
...
     },
     methods: {
+        validateRejectedProduct: function (type, product) {
+            if(product['rejected_'+type]){
+                if(product[type] == null || Object.keys(product[type]).length === 0 || product.length === 0){
+                    return true
+                }else{
+                    return false
+                }
+            }
```
Comment (cyberhck) [inline assets/app.js]: what does it return in else case? when `if(product['rejected_' + type])` evaluates to false, I think it don't return anything which will evaluate to undefined, maybe return something at the end too?

File: assets/app.js [hunk 6]
```diff
@@ -737,6 +770,16 @@ new Vue({
         }
     },
     methods: {
+        validateRejectedProduct: function (type, product) {
+            if(product['rejected_'+type]){
+                if(product[type] == null || Object.keys(product[type]).length === 0 || product.length === 0){
```
Comment (cyberhck) [inline assets/app.js]: instead of doing if(...), I'd just `return product[type] == null || Object.keys(product[type]).length === 0 || product.length === 0`

thoughts?

**Review by cyberhck — COMMENTED** [review]
PS Comments
